# 2022-01-06: ubuntu:latest = 20.04, ubuntu:rolling = 21.10, ubuntu:devel = 22.04
# See https://hub.docker.com/_/ubuntu
image: ubuntu:rolling

stages:
  - build
  - deploy

website_build:
  stage: build
  variables:
    # If docbook-xsl is installed, the xsltproc command reads
    # stylesheets from local files instead of http://docbook.sourceforge.net.
    # Faster and safer. Reading from docbook.sourceforge.net sometimes fails.
    DEPENDENCIES:
      meson
      ninja-build
      yelp-tools
      gettext
      itstool
      libxml2-utils
      xsltproc
      docbook-xml
      docbook-xsl
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update && apt -y upgrade && apt -y install $DEPENDENCIES
    - mkdir _build && cd _build
    - meson --prefix=/usr
    - meson compile
  artifacts:
    paths:
      - _build/docs/html

# Publish the gtkmm website at gnome.pages.gitlab.gnome.org/gnomemm-website
pages:
  stage: deploy
  script:
    - mkdir public
    - mv _build/docs/html/.htaccess _build/docs/html/* public
  artifacts:
    paths:
      - public
  only:
    - master
